
spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FAlSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 'zeynali2001'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
