#server:
#  port: 8090
#  servlet:
#    context-path: /api
#
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/onlineShop
#    username: mnsure
#    password: Mytestp@ssword12
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      cache:
#        use_second_level_cache: false
#        use_query_cache: false
#      ddl-auto: create
#      show-sql: true
spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
